# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/HDMIBreakout.xdc

# Block Designs: bd/HDMIZYBOZ7/HDMIZYBOZ7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMIZYBOZ7 || ORIG_REF_NAME==HDMIZYBOZ7} -quiet] -quiet

# IP: bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_BreakoutPixelGenerat_0_0/HDMIZYBOZ7_BreakoutPixelGenerat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMIZYBOZ7_BreakoutPixelGenerat_0_0 || ORIG_REF_NAME==HDMIZYBOZ7_BreakoutPixelGenerat_0_0} -quiet] -quiet

# IP: bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_dvid_generator_0_0/HDMIZYBOZ7_dvid_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMIZYBOZ7_dvid_generator_0_0 || ORIG_REF_NAME==HDMIZYBOZ7_dvid_generator_0_0} -quiet] -quiet

# IP: bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_clk_wiz_0_0/HDMIZYBOZ7_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMIZYBOZ7_clk_wiz_0_0 || ORIG_REF_NAME==HDMIZYBOZ7_clk_wiz_0_0} -quiet] -quiet

# IP: bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_processing_system7_0_0/HDMIZYBOZ7_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMIZYBOZ7_processing_system7_0_0 || ORIG_REF_NAME==HDMIZYBOZ7_processing_system7_0_0} -quiet] -quiet

# IP: bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_axi_gpio_0_0/HDMIZYBOZ7_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMIZYBOZ7_axi_gpio_0_0 || ORIG_REF_NAME==HDMIZYBOZ7_axi_gpio_0_0} -quiet] -quiet

# IP: bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_axi_gpio_1_0/HDMIZYBOZ7_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMIZYBOZ7_axi_gpio_1_0 || ORIG_REF_NAME==HDMIZYBOZ7_axi_gpio_1_0} -quiet] -quiet

# IP: bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_xbar_1/HDMIZYBOZ7_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMIZYBOZ7_xbar_1 || ORIG_REF_NAME==HDMIZYBOZ7_xbar_1} -quiet] -quiet

# IP: bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_ps7_0_axi_periph_0/HDMIZYBOZ7_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMIZYBOZ7_ps7_0_axi_periph_0 || ORIG_REF_NAME==HDMIZYBOZ7_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_rst_ps7_0_50M_0/HDMIZYBOZ7_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMIZYBOZ7_rst_ps7_0_50M_0 || ORIG_REF_NAME==HDMIZYBOZ7_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_axi_gpio_2_1/HDMIZYBOZ7_axi_gpio_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMIZYBOZ7_axi_gpio_2_1 || ORIG_REF_NAME==HDMIZYBOZ7_axi_gpio_2_1} -quiet] -quiet

# IP: bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_auto_pc_0/HDMIZYBOZ7_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMIZYBOZ7_auto_pc_0 || ORIG_REF_NAME==HDMIZYBOZ7_auto_pc_0} -quiet] -quiet

# XDC: bd/HDMIZYBOZ7/HDMIZYBOZ7_ooc.xdc
