# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/OAkun/Desktop/PersonalProject/HDMIZYBOZ7BreakoutFinal/HDMIZYBOZ7BreakoutFinal.srcs/sources_1/bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_rst_ps7_0_50M_0/HDMIZYBOZ7_rst_ps7_0_50M_0.xci
# IP: The module: 'HDMIZYBOZ7_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OAkun/Desktop/PersonalProject/HDMIZYBOZ7BreakoutFinal/HDMIZYBOZ7BreakoutFinal.srcs/sources_1/bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_rst_ps7_0_50M_0/HDMIZYBOZ7_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMIZYBOZ7_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OAkun/Desktop/PersonalProject/HDMIZYBOZ7BreakoutFinal/HDMIZYBOZ7BreakoutFinal.srcs/sources_1/bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_rst_ps7_0_50M_0/HDMIZYBOZ7_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMIZYBOZ7_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/OAkun/Desktop/PersonalProject/HDMIZYBOZ7BreakoutFinal/HDMIZYBOZ7BreakoutFinal.srcs/sources_1/bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_rst_ps7_0_50M_0/HDMIZYBOZ7_rst_ps7_0_50M_0.xci
# IP: The module: 'HDMIZYBOZ7_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OAkun/Desktop/PersonalProject/HDMIZYBOZ7BreakoutFinal/HDMIZYBOZ7BreakoutFinal.srcs/sources_1/bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_rst_ps7_0_50M_0/HDMIZYBOZ7_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMIZYBOZ7_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OAkun/Desktop/PersonalProject/HDMIZYBOZ7BreakoutFinal/HDMIZYBOZ7BreakoutFinal.srcs/sources_1/bd/HDMIZYBOZ7/ip/HDMIZYBOZ7_rst_ps7_0_50M_0/HDMIZYBOZ7_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMIZYBOZ7_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
